name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: movie-management-api
  REGION: europe-west1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Docker to Artifact Registry
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://europe-west1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/gcr.io/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/gcr.io/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/gcr.io/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --set-env-vars=NODE_ENV=prod,\
              DATABASE_URL=${{ secrets.DATABASE_URL }},\
              JWT_SECRET=${{ secrets.JWT_SECRET }},\
              JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }},\
              INITIAL_MANAGER_EMAIL=${{ secrets.INITIAL_MANAGER_EMAIL }},\
              INITIAL_MANAGER_PASSWORD=${{ secrets.INITIAL_MANAGER_PASSWORD }},\
              INITIAL_MANAGER_USERNAME=${{ secrets.INITIAL_MANAGER_USERNAME }},\
              INITIAL_USER_EMAIL=${{ secrets.INITIAL_USER_EMAIL }},\
              INITIAL_USER_PASSWORD=${{ secrets.INITIAL_USER_PASSWORD }},\
              INITIAL_USER_USERNAME=${{ secrets.INITIAL_USER_USERNAME }}